### ISSUE TITLE
Not able to set cairo-ls settings in Helix

### ISSUE THREAD

**Issue by Eikix** [ericglau/cairo-ls#47]

**Comment by Eikix** [comment]
For reference: https://github.com/helix-editor/helix/issues/5245

**Comment by ericglau** [comment]
Sorry for the late response. From the thread above, it looks like some settings are being passed through to the language server, but you have additional source files in certain folders that are not recognized during compilation. Is that correct?

The language server also has a `cairoPath` setting that takes an array of strings representing additional locations to search for cairo files.

Can you try something like this?
```
config = { <the other settings that you currently have>, cairoPath = [ "your additional path" ] }
```

**Comment by Eikix** [comment]
Hi:)! 

I tried this: 
```toml
[[language]]
config = { cairoPath = [
  "/Users/eliastazartes/code/theodo/kakarot/src",
  "/Users/eliastazartes/code/theodo/kakarot",
  "/Users/eliastazartes/code/theodo/kakarot/tests",
"tests",
"lib"
], sourceDir = "src", venvCommand = "source ~/cairo_venv/bin/activate", nileUseVenv = false, useVenv = true, nileVenvCommand = "source ~/cairo_venv/bin/activate" }
name = "cairo"
scope = "source.cairo"
injection-regex = "cairo"
file-types = ["cairo"]
indent = { tab-width = 2, unit = "  " }
comment-token = "#"
language-server = { command = "cairols.sh" }
```

And it does not work:
![image](https://user-images.githubusercontent.com/66871571/214264304-2e360ec1-260e-4a36-b0c9-f1260c5a5042.png)



But it appears the language server can't read this config somehow.
I'm trying to pass the arguments in my bash script:

```
node ~/code/lsp/node_modules/cairo-ls/out/server.js --stdio --sourceDir="src" --venvCommand="source ~/cairo_venv/bin/activate" --nileUseVenv=false --useVenv=true --nileVenvCommand="" --cairoPath="['/Users/eliastazartes/code/theodo/kakarot/src', '/Users/eliastazartes/code/theodo/kakarot','/Users/eliastazartes/code/theodo/kakarot/tests']"

```
